/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ShoeListing = IDL.Record({
  'id' : IDL.Nat,
  'conditionScore' : IDL.Nat,
  'name' : IDL.Text,
  'seller' : IDL.Principal,
  'photo' : ExternalBlob,
  'isAuthentic' : IDL.Bool,
  'priceCents' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'completeTrade' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Nat, ExternalBlob, IDL.Nat, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'getListings' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Bool],
      [IDL.Vec(ShoeListing)],
      [],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'collection' : IDL.Vec(ShoeListing),
          'tradeCount' : IDL.Nat,
          'averageRating' : IDL.Float64,
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ShoeListing = IDL.Record({
    'id' : IDL.Nat,
    'conditionScore' : IDL.Nat,
    'name' : IDL.Text,
    'seller' : IDL.Principal,
    'photo' : ExternalBlob,
    'isAuthentic' : IDL.Bool,
    'priceCents' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'completeTrade' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'createListing' : IDL.Func(
        [IDL.Text, IDL.Nat, ExternalBlob, IDL.Nat, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'getListings' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Bool],
        [IDL.Vec(ShoeListing)],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'collection' : IDL.Vec(ShoeListing),
            'tradeCount' : IDL.Nat,
            'averageRating' : IDL.Float64,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };